language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - TYPO3_VERSION=^7.6 COVERAGE=0
  - TYPO3_VERSION=^8.7 COVERAGE=0
  - TYPO3_VERSION=^9.5 COVERAGE=0

matrix:
  include:
    - env: TYPO3_VERSION=^7.6 COVERAGE=1
      php: 7.0
  exclude:
    - env: TYPO3_VERSION=^9.5 COVERAGE=0
      php: 7.0
    - env: TYPO3_VERSION=^9.5 COVERAGE=0
      php: 7.1

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  # Installs TYPO3
  - composer require --dev nimut/typo3-complete=$TYPO3_VERSION
    # Restore composer.json
  - git checkout composer.json
  - export "TYPO3_PATH_WEB"=$PWD/.Build/Web;
  # Locating UnitTests.xml
  - export "UNIT_XML"='.Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml'
  - export "FUNCTIONAL_XML"='.Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml'

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --colors -c $UNIT_XML Tests/Unit
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --whitelist Classes/ --coverage-clover=unittest-coverage.clover --colors -c $UNIT_XML Tests/Unit
    fi
  - >
    if [[ "$COVERAGE" == "0" ]]; then
          echo;
          echo "Running functional tests";
          export typo3DatabaseName="typo3";
          export typo3DatabaseHost="localhost";
          export typo3DatabaseUsername="root";
          export typo3DatabasePassword="";
          .Build/bin/phpunit --whitelist Classes/ --colors -c $FUNCTIONAL_XML Tests/Functional
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running functional tests";
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      .Build/bin/phpunit --whitelist Classes/ --coverage-clover=functional-coverage.clover --colors -c $FUNCTIONAL_XML Tests/Functional
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
      php ocular.phar code-coverage:upload --format=php-clover functional-coverage.clover
    fi
  - >
    echo;
    echo "Running php lint";
    /bin/bash -c "
        if ! find typo3conf/ext/felogin_bruteforce_protection -name \*.php | parallel --gnu 'php -l {}' > /tmp/errors 2>&1; then
            grep -v \"No syntax errors detected in\" /tmp/errors;
            exit 99;
        fi
    "
