services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Aoe\FeloginBruteforceProtection\:
    resource: '../Classes/*'

  Aoe\FeloginBruteforceProtection\Command\CleanUpCommand:
    tags:
      - name: 'console.command'
        command: 'aoe:feloginbruteforceprotection:cleanup'
